"""LLM backends for resolving a merge-conflicted file.

Two backends, identical contract: given a `ResolveRequest`, edit
`req.file_path` in place to remove the conflict markers. The orchestrator
calls `resolve_file(req, cfg)` and never sees the backend difference.

- claude: Claude Code CLI in headless mode (`claude -p`). Auth via
  CLAUDE_CODE_OAUTH_TOKEN (generated by `claude setup-token` on a desktop
  logged into Claude Pro/Max). No API key, no per-token charges.
- codex: OpenAI Codex CLI (`codex exec`). Auth via `codex login` on the host.
  No API key, no per-token charges.
"""

from __future__ import annotations

import asyncio
import os
from dataclasses import dataclass
from pathlib import Path

from .config import LLMConfig


class LLMError(RuntimeError):
    pass


@dataclass(frozen=True)
class ResolveRequest:
    repo_dir: Path
    file_path: str
    head_diff: str       # PR-side intent: git diff --merge-base <base> HEAD -- <file>
    base_diff: str       # base-side intent: git diff --merge-base HEAD <base> -- <file>
    conflicted_content: str  # current on-disk content with zdiff3 markers


PROMPT_TEMPLATE = """\
You are resolving a Git merge conflict in a single file. The file is at:

    {file_path}

It currently contains zdiff3-style conflict markers (`<<<<<<<`, `|||||||` for the merge base,
`=======`, `>>>>>>>`).

Below is the semantic context:

=== PR's intent on this file (diff from merge base to PR HEAD) ===
{head_diff}

=== Base branch's intent on this file (diff from merge base to base HEAD) ===
{base_diff}

=== Current file with conflict markers ===
{conflicted_content}

Resolve the conflict by writing the merged file content back to {file_path}. Preserve
both sides' semantic intent where they don't actually conflict; when they do conflict,
prefer the change that keeps the codebase consistent and tests passing. Do NOT add
explanatory comments about the merge. Do NOT leave any conflict markers. Do NOT modify
any file other than {file_path}.

When you are done, the file at {file_path} must contain valid source code with no
remaining conflict markers.
"""


async def resolve_file(req: ResolveRequest, cfg: LLMConfig, *, timeout: float = 300.0) -> None:
    if cfg.backend == "claude":
        await _resolve_with_claude(req, cfg, timeout=timeout)
    elif cfg.backend == "codex":
        await _resolve_with_codex(req, cfg, timeout=timeout)
    else:
        raise LLMError(
            f"unknown LLM_BACKEND: {cfg.backend!r}; supported: 'claude', 'codex'"
        )


def _build_prompt(req: ResolveRequest) -> str:
    return PROMPT_TEMPLATE.format(
        file_path=req.file_path,
        head_diff=req.head_diff or "(no PR-side changes — file was unchanged on PR branch)",
        base_diff=req.base_diff or "(no base-side changes — file was unchanged on base)",
        conflicted_content=req.conflicted_content,
    )


async def _run(cmd: list[str], *, cwd: Path | None, env: dict[str, str], timeout: float) -> None:
    proc = await asyncio.create_subprocess_exec(
        *cmd,
        cwd=str(cwd) if cwd else None,
        env=env,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    try:
        stdout_b, stderr_b = await asyncio.wait_for(proc.communicate(), timeout=timeout)
    except TimeoutError as e:
        proc.kill()
        await proc.wait()
        raise LLMError(f"{cmd[0]} timed out after {timeout}s") from e
    if proc.returncode != 0:
        raise LLMError(
            f"{cmd[0]} failed (rc={proc.returncode}):\n"
            f"stdout:\n{stdout_b.decode(errors='replace')}\n"
            f"stderr:\n{stderr_b.decode(errors='replace')}"
        )


async def _resolve_with_claude(req: ResolveRequest, cfg: LLMConfig, *, timeout: float) -> None:
    cmd = [
        cfg.resolved_binary(),
        "-p",
        "--dangerously-skip-permissions",
        *cfg.extra_args,
        _build_prompt(req),
    ]
    env = os.environ.copy()
    if cfg.oauth_token:
        env["CLAUDE_CODE_OAUTH_TOKEN"] = cfg.oauth_token
    await _run(cmd, cwd=req.repo_dir, env=env, timeout=timeout)


async def _resolve_with_codex(req: ResolveRequest, cfg: LLMConfig, *, timeout: float) -> None:
    cmd = [
        cfg.resolved_binary(),
        "exec",
        "--full-auto",
        "--sandbox", cfg.sandbox,
        "--cd", str(req.repo_dir),
        *cfg.extra_args,
        _build_prompt(req),
    ]
    await _run(cmd, cwd=None, env=os.environ.copy(), timeout=timeout)
